extends Node

enum JOB{NONE, BLACKSMITH, KING, MINER, FARMER, DOCTER, SALESMAN, POTTER, STABLEMASTER, CARPENTER, BUILDER, HUNTER, INVENTOR, CHEF}
enum SKILL_LEVEL{NONE, NOVICE, APPRENTICE, JOURNEYMAN, EXPERT, MASTER}
enum BEHAVIOR_TYPE{IDLE, WANDER, STAND, WORK}
enum GENDER{MALE,FEMALE}
