extends Node

var tiles: Dictionary = {}

func get_tile(id: int) -> TileDropData:
	if tiles.has(id):
		if tiles[id] is String:
			tiles[id] = load(tiles[id]) as TileDropData
		return tiles[id] as TileDropData
	return null

func _ready():
	const FOLDER_PATH = "res://assets/resources/drops/"
	tiles[0] = FOLDER_PATH + "dirt_slope_drop.tres"
	tiles[1] = FOLDER_PATH + "dirt_stair_exterior_corner_drop.tres"
	tiles[2] = FOLDER_PATH + "dirt_stair_interior_corner_drop.tres"
	tiles[3] = FOLDER_PATH + "dirt_stairs_drop.tres"
	tiles[4] = FOLDER_PATH + "dirt_drop.tres"
	tiles[5] = FOLDER_PATH + "grass_slope_drop.tres"
	tiles[6] = FOLDER_PATH + "grass_drop.tres"
	tiles[7] = FOLDER_PATH + "brick_slope_drop.tres"
	tiles[8] = FOLDER_PATH + "brick_stair_exterior_corner_drop.tres"
	tiles[9] = FOLDER_PATH + "brick_stair_interior_corner_drop.tres"
	tiles[10] = FOLDER_PATH + "brick_stairs_drop.tres"
	tiles[11] = FOLDER_PATH + "bricks_drop.tres"
	tiles[12] = FOLDER_PATH + "brick_wall_drop.tres"
	tiles[13] = FOLDER_PATH + "marble_slope_drop.tres"
	tiles[14] = FOLDER_PATH + "marble_stair_exterior_corner_drop.tres"
	tiles[15] = FOLDER_PATH + "marble_stair_interior_corner_drop.tres"
	tiles[16] = FOLDER_PATH + "marble_stairs_drop.tres"
	tiles[17] = FOLDER_PATH + "marble_drop.tres"
	tiles[18] = FOLDER_PATH + "marble_wall_drop.tres"
	tiles[19] = FOLDER_PATH + "marble_brick_slope_drop.tres"
	tiles[20] = FOLDER_PATH + "marble_brick_stair_exterior_corner_drop.tres"
	tiles[21] = FOLDER_PATH + "marble_brick_stair_interior_corner_drop.tres"
	tiles[22] = FOLDER_PATH + "marble_brick_stairs_drop.tres"
	tiles[23] = FOLDER_PATH + "marble_brick_drop.tres"
	tiles[24] = FOLDER_PATH + "marble_brick_wall_drop.tres"
	tiles[25] = FOLDER_PATH + "log_slope_drop.tres"
	tiles[26] = FOLDER_PATH + "log_drop.tres"
	tiles[27] = FOLDER_PATH + "stone_slope_drop.tres"
	tiles[28] = FOLDER_PATH + "stone_stair_exterior_corner_drop.tres"
	tiles[29] = FOLDER_PATH + "stone_stair_interior_corner_drop.tres"
	tiles[30] = FOLDER_PATH + "stone_stairs_drop.tres"
	tiles[31] = FOLDER_PATH + "stone_drop.tres"
	tiles[32] = FOLDER_PATH + "stone_wall_drop.tres"
	tiles[33] = FOLDER_PATH + "stone_brick_slope_drop.tres"
	tiles[34] = FOLDER_PATH + "stone_brick_stair_exterior_corner_drop.tres"
	tiles[35] = FOLDER_PATH + "stone_brick_stair_interior_corner_drop.tres"
	tiles[36] = FOLDER_PATH + "stone_brick_stairs_drop.tres"
	tiles[37] = FOLDER_PATH + "stone_bricks_drop.tres"
	tiles[38] = FOLDER_PATH + "stone_brick_wall_drop.tres"
	tiles[39] = FOLDER_PATH + "sand_drop.tres"
	tiles[40] = FOLDER_PATH + "sand_slope_drop.tres"
	#tiles[41] = null # Water Tile
	tiles[42] = FOLDER_PATH + "coin_item_drop.tres"
	tiles[43] = FOLDER_PATH + "coal_item_drop.tres"
	tiles[44] = FOLDER_PATH + "gold_item_drop.tres"
	tiles[45] = FOLDER_PATH + "iron_item_drop.tres"
	tiles[46] = FOLDER_PATH + "lumber.tres"
	tiles[47] = FOLDER_PATH + "lumber.tres"
	tiles[48] = FOLDER_PATH + "lumber.tres"
	tiles[49] = FOLDER_PATH + "stone_item_drop.tres"
	tiles[50] = FOLDER_PATH + "rough_stone_drop.tres"
	tiles[51] = FOLDER_PATH + "rough_stone_slope_drop.tres"
	tiles[52] = FOLDER_PATH + "rough_stone_wall_drop.tres"
	tiles[53] = FOLDER_PATH + "rough_stone_stair_interior_corner_drop.tres"
	tiles[54] = FOLDER_PATH + "rough_stone_stair_drop.tres"
	tiles[55] = FOLDER_PATH + "rough_stone_stair_exterior_corner_drop.tres"
	tiles[56] = FOLDER_PATH + "polished_stone_drop.tres"
	tiles[57] = FOLDER_PATH + "polished_stone_stair_interior_corner_drop.tres"
	tiles[58] = FOLDER_PATH + "polished_stone_stair_drop.tres"
	tiles[59] = FOLDER_PATH + "polished_stone_stair_exterior_corner_drop.tres"
	tiles[60] = FOLDER_PATH + "polished_stone_slope_drop.tres"
	tiles[61] = FOLDER_PATH + "polished_stone_wall_drop.tres"
	tiles[62] = FOLDER_PATH + "polished_stone_pole_drop.tres"
	tiles[63] = FOLDER_PATH + "mud_slope_drop.tres"
	tiles[64] = FOLDER_PATH + "mud_drop.tres"
	tiles[65] = FOLDER_PATH + "tree_drop.tres"
	tiles[66] = FOLDER_PATH + "tree_small_drop.tres"
