name: "Build Release"
on: workflow_dispach

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export
    steps:
    - name: checkout
      uses: actions/checkout@v4
  
    - name: export game
      id: export
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: false
        tag: testing_release
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
